require:

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - bin/bundle

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/Documentation:
  # Skips checking to make sure top level modules / classes have a comment.
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 150

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - "**/*.rake"
    - "config/environments/*.rb"
    - "test/**/*_test.rb"
    - "*.gemspec"
    - "Gemfile"

Metrics/ModuleLength:
  Exclude:
    - "**/concerns/**/*.rb"

Metrics/ClassLength:
  Exclude:
    - "test/**/*.rb"

Rails/LexicallyScopedActionFilter:
  Exclude:
    - "**/concerns/**/*.rb"

Rails/SkipsModelValidations:
  Exclude:
    - "test/**/*.rb"
